services:
  - type: web
    name: formgen-frontend
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: npm start
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - next.config.mjs

  - type: web
    name: formgen-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    region: oregon
    buildFilter:
      paths:
        - backend/**
        - backend/requirements.txt
